export const AVAILABLE_ICONS = [
  'Briefcase',
  'Wallet',
  'CreditCard',
  'PiggyBank',
  'Landmark',
  'Building',
  'Home',
  'Car',
  'Plane',
  'Heart',
  'Star',
  'Gift',
  'Trophy',
  'Shield',
  'Key',
  'Lock',
  'Coins',
  'Banknote',
  'Gem',
  'Safe',
  'Tag',
  'Coffee',
  'ShoppingCart',
  'Gamepad2',
  'Utensils',
  'Smartphone',
  'Zap',
  'Music',
  'Camera',
  'Book',
  'Monitor',
  'GraduationCap',
];

export const AVAILABLE_COLORS = ['#ef4444', '#f97316', '#f59e0b', '#84cc16', '#22c55e', '#10b981', '#06b6d4', '#0ea5e9', '#3b82f6', '#6366f1', '#8b5cf6', '#d946ef', '#ec4899', '#f43f5e'];
